// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddDataSrc: typeof import('./src/components/DataBase/addDataSrc.vue')['default'];
    Catalogue: typeof import('./src/components/Catalogue/Catalogue.vue')['default'];
    DataBase: typeof import('./src/components/DataBase/DataBase.vue')['default'];
    InterFace: typeof import('./src/components/InterFace/InterFace.vue')['default'];
    ManageMent: typeof import('./src/components/management/ManageMent.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    Scriptment: typeof import('./src/components/Scriptment/Scriptment.vue')['default'];
    TableManagement: typeof import('./src/components/TableManagement/TableManagement.vue')['default'];
    Taskment: typeof import('./src/components/Taskment/Taskment.vue')['default'];
  }
}

export {};
